export const reactQuizQuestions = [
  {
    id: 1,
    question: "What is React primarily used for?",
    options: [
      "Building user interfaces from reusable components",
      "Managing relational databases",
      "Compiling JavaScript into machine code",
      "Creating operating-system drivers",
    ],
    correctOption: 0,
  },
  {
    id: 2,
    question: "What does JSX let you write?",
    options: [
      "SQL queries inside CSS",
      "Markup-like syntax inside JavaScript",
      "JavaScript inside JSON files only",
      "HTML that runs without JavaScript",
    ],
    correctOption: 1,
  },
  {
    id: 3,
    question: "How does a parent component usually pass data to a child component?",
    options: ["Through the DOM", "Through CSS selectors", "Through props", "Through local storage"],
    correctOption: 2,
  },
  {
    id: 4,
    question: "What is React state used for?",
    options: [
      "Static values that are shared by every browser tab",
      "CSS rules for a component",
      "Values that can only be set by the server",
      "Values that can change and cause a component to render again",
    ],
    correctOption: 3,
  },
  {
    id: 5,
    question: "What does the useState Hook return?",
    options: [
      "The current state value and a function to update it",
      "A DOM node and an event handler",
      "A promise and its error handler",
      "A component and its props",
    ],
    correctOption: 0,
  },
  {
    id: 6,
    question: "Where should you call React Hooks such as useState?",
    options: [
      "Inside loops so each item can have separate state",
      "At the top level of a function component or custom Hook",
      "Inside event handlers only",
      "Anywhere in a JavaScript file",
    ],
    correctOption: 1,
  },
  {
    id: 7,
    question: "Why should list items have stable keys?",
    options: [
      "To prevent components from receiving props",
      "To make every item render on the server",
      "To help React identify which items changed, moved, or were removed",
      "To sort the list alphabetically",
    ],
    correctOption: 2,
  },
  {
    id: 8,
    question: "Which Hook is commonly used to synchronize a component with an external system?",
    options: ["useMemo", "useState", "useId", "useEffect"],
    correctOption: 3,
  },
  {
    id: 9,
    question: "What does an empty dependency array in useEffect generally indicate?",
    options: [
      "The Effect has no dependencies and runs after the initial mount; its cleanup runs on unmount",
      "The Effect should re-run after every state update",
      "The Effect is disabled permanently, including on mount",
      "The Effect runs only when the browser tab is focused",
    ],
    correctOption: 0,
  },
  {
    id: 10,
    question: "What makes an input a controlled component in React?",
    options: [
      "Its value is managed only by the browser",
      "Its value is driven by React state and updated through an event handler",
      "It can only accept numeric values",
      "It is hidden until the page loads",
    ],
    correctOption: 1,
  },
  {
    id: 11,
    question: "What is a cleanup function returned from useEffect commonly used for?",
    options: [
      "Resetting every component's state after each render",
      "Preventing the component from mounting",
      "Removing listeners or stopping subscriptions when they are no longer needed",
      "Clearing the browser's entire cache",
    ],
    correctOption: 2,
  },
  {
    id: 12,
    question: "What problem does React Context help solve?",
    options: [
      "Automatically validating every form field",
      "Converting class components into functions",
      "Replacing all component state with a database",
      "Passing shared values through many component levels without forwarding props at each level",
    ],
    correctOption: 3,
  },
  {
    id: 13,
    question: "What does lifting state up mean?",
    options: [
      "Moving shared state to the closest common parent of the components that use it",
      "Moving state into a CSS file",
      "Copying state into every child component",
      "Saving all state in local storage",
    ],
    correctOption: 0,
  },
  {
    id: 14,
    question: "What is React.memo primarily intended to do?",
    options: [
      "Store data between browser sessions",
      "Skip re-rendering a component when its props have not changed",
      "Memoize every function in an application automatically",
      "Prevent a component from receiving new props",
    ],
    correctOption: 1,
  },
  {
    id: 15,
    question: "Which statement about useRef is correct?",
    options: [
      "It updates state and always triggers a render",
      "It can only store DOM elements and nothing else",
      "It stores a mutable value between renders without triggering a render when changed",
      "It replaces props for child components",
    ],
    correctOption: 2,
  },
  {
    id: 16,
    question: "How can a component conditionally display different content?",
    options: [
      "Use a CSS media query to change the component tree",
      "Call a Hook conditionally",
      "Change the component's file extension at runtime",
      "Use JavaScript expressions such as a ternary or logical AND in its JSX",
    ],
    correctOption: 3,
  },
  {
    id: 17,
    question: "What is the recommended way to update an object stored in React state?",
    options: [
      "Create a new object with the changed values instead of mutating the existing object",
      "Change the object directly and do not call the setter",
      "Convert the object to a DOM element",
      "Edit the object's source file",
    ],
    correctOption: 0,
  },
  {
    id: 18,
    question: "How do you typically handle a click event in JSX?",
    options: [
      "Add a click() attribute containing a string of JavaScript",
      "Add an onClick prop with a function, such as onClick={handleClick}",
      "Use a CSS :click selector",
      "Call the handler while rendering, such as onClick={handleClick()}",
    ],
    correctOption: 1,
  },
  {
    id: 19,
    question: "What does a React Fragment do?",
    options: [
      "Creates a separate JavaScript thread for each child",
      "Prevents child components from rendering",
      "Groups multiple elements without adding an extra DOM element",
      "Adds a hidden div around every element",
    ],
    correctOption: 2,
  },
  {
    id: 20,
    question: "What naming convention should a custom Hook follow?",
    options: [
      "Its name should end with Component",
      "Its name must match a browser event",
      "Its name must be written in uppercase",
      "Its name should start with use, such as useWindowSize",
    ],
    correctOption: 3,
  },
] as const;
